###################
# Dockerfile
#
# This is the docker file for devops overflow.
# This can be used to build a docker image that runs a built version of devops overflow.
# This docker image will contain the GO api web server and the NextJs static html
###################

# First use a docker node image to build to nextjs static HTML using node
# The export command creates a folder /app/out with the html generated by build
FROM node:14-alpine as nextjsbuild
WORKDIR /app

COPY src/ui .
RUN npm ci
RUN npm run build
RUN npm run export

# Then use a golang image to build the golang server main from code
FROM golang:alpine as gobuild
WORKDIR /app/main

COPY src/server .
RUN go get -d -v ./...
RUN go build
RUN chmod +x main

# Finally create a small alpine image with just the main and the static HTML
FROM alpine
WORKDIR /app/main

COPY --from=nextjsbuild /app/out /app/main/html
COPY --from=gobuild /app/main/main /app/main/main
COPY --from=gobuild /app/main/config.yaml /app/main/config.yaml

RUN chmod +x /app/main/main
CMD ["/app/main/main"]



