###################
# Dockerfile
#
# This is the docker file for devops overflow.
# This can be used to build a docker image that runs a built version of devops overflow.
# This docker image will contain the GO api web server and the NextJs static html
###################

# First use a scratch docker container to build to nextjs UI build using node
FROM node:14-alpine as nextjsbuild
WORKDIR /app

# The export command creates a folder /app/out with the html generated by build
COPY src/ui .
RUN npm ci
RUN npm run build
RUN npm run export

# Then create a golang image to build and run the golang server code
FROM golang:latest
WORKDIR /app/main

COPY src/server .
COPY --from=nextjsbuild /app/out /app/main/html
RUN go get -d -v ./...
RUN go build
RUN chmod +x main
CMD ["./main"]

